# Generated by Django 5.2.2 on 2025-06-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0002_entrylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GUARD', 'Guard'), ('DRIVER', 'Driver'), ('ORG_MANAGER', 'Org Manager')], default='ADMIN', max_length=20),
        ),
    ]
