# Generated by Django 5.2.2 on 2025-06-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_org_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_face_registered',
            field=models.BooleanField(default=False),
        ),
    ]
