apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: vms
type: Opaque
data:
  password: MTIzNDU=  # base64 encoded "12345"

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: vms
type: Opaque
data:
  auth-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjEyMzQ1QHBvc3RncmVzL3Ztc19hdXRo  # base64 encoded connection string

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: vms
type: Opaque
data:
  secret-key: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # base64 encoded JWT secret